// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: inner.proto

package transport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InnerClient is the client API for Inner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InnerClient interface {
	RouteRpc(ctx context.Context, in *RouteRpcReq, opts ...grpc.CallOption) (*RouteRpcRsp, error)
	HttpRpc(ctx context.Context, in *HttpRpcReq, opts ...grpc.CallOption) (*HttpRpcRsp, error)
}

type innerClient struct {
	cc grpc.ClientConnInterface
}

func NewInnerClient(cc grpc.ClientConnInterface) InnerClient {
	return &innerClient{cc}
}

func (c *innerClient) RouteRpc(ctx context.Context, in *RouteRpcReq, opts ...grpc.CallOption) (*RouteRpcRsp, error) {
	out := new(RouteRpcRsp)
	err := c.cc.Invoke(ctx, "/transport.Inner/RouteRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *innerClient) HttpRpc(ctx context.Context, in *HttpRpcReq, opts ...grpc.CallOption) (*HttpRpcRsp, error) {
	out := new(HttpRpcRsp)
	err := c.cc.Invoke(ctx, "/transport.Inner/HttpRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InnerServer is the server API for Inner service.
// All implementations must embed UnimplementedInnerServer
// for forward compatibility
type InnerServer interface {
	RouteRpc(context.Context, *RouteRpcReq) (*RouteRpcRsp, error)
	HttpRpc(context.Context, *HttpRpcReq) (*HttpRpcRsp, error)
	mustEmbedUnimplementedInnerServer()
}

// UnimplementedInnerServer must be embedded to have forward compatible implementations.
type UnimplementedInnerServer struct {
}

func (UnimplementedInnerServer) RouteRpc(context.Context, *RouteRpcReq) (*RouteRpcRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RouteRpc not implemented")
}
func (UnimplementedInnerServer) HttpRpc(context.Context, *HttpRpcReq) (*HttpRpcRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HttpRpc not implemented")
}
func (UnimplementedInnerServer) mustEmbedUnimplementedInnerServer() {}

// UnsafeInnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InnerServer will
// result in compilation errors.
type UnsafeInnerServer interface {
	mustEmbedUnimplementedInnerServer()
}

func RegisterInnerServer(s grpc.ServiceRegistrar, srv InnerServer) {
	s.RegisterService(&Inner_ServiceDesc, srv)
}

func _Inner_RouteRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerServer).RouteRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.Inner/RouteRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerServer).RouteRpc(ctx, req.(*RouteRpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inner_HttpRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerServer).HttpRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.Inner/HttpRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerServer).HttpRpc(ctx, req.(*HttpRpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Inner_ServiceDesc is the grpc.ServiceDesc for Inner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transport.Inner",
	HandlerType: (*InnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RouteRpc",
			Handler:    _Inner_RouteRpc_Handler,
		},
		{
			MethodName: "HttpRpc",
			Handler:    _Inner_HttpRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inner.proto",
}
